[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:420 scaling database to zero units
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:424 scaling database to three units
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql-k8s (waiting for exactly 3 units, current : 0)
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql-k8s/0 [executing] maintenance: installing charm software
  postgresql-k8s/1 [executing] maintenance: installing charm software
  postgresql-k8s/2 [executing] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql-k8s/0 [idle] unknown: 
  postgresql-k8s/1 [executing] waiting: awaiting for cluster to start
  postgresql-k8s/2 [idle] unknown: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql-k8s/0 [idle] unknown: 
  postgresql-k8s/1 [executing] waiting: awaiting for primary endpoint to be ready
  postgresql-k8s/2 [idle] unknown: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql-k8s/0 [idle] unknown: 
  postgresql-k8s/1 [idle] active: Primary
  postgresql-k8s/2 [idle] unknown: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql-k8s/0 [idle] waiting: awaiting for cluster to start
  postgresql-k8s/1 [executing] maintenance: reconfiguring cluster
  postgresql-k8s/2 [idle] waiting: awaiting for cluster to start
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql-k8s/0 [idle] active: 
  postgresql-k8s/1 [idle] active: Primary
  postgresql-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql-k8s/0 [executing] active: 
  postgresql-k8s/1 [idle] active: Primary
  postgresql-k8s/2 [executing] active: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql-k8s/0 [executing] active: 
  postgresql-k8s/1 [idle] active: Primary
  postgresql-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql-k8s/0 [idle] active: 
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:428 waiting for the database service to start in all units
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:434 checking whether writes are increasing
[32mINFO    [0m httpx:_client.py:1026 HTTP Request: GET https://10.1.0.107:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1026 HTTP Request: GET https://10.1.0.107:16443/api/v1/namespaces/test/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1026 HTTP Request: GET https://10.1.0.107:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1026 HTTP Request: GET https://10.1.0.107:16443/api/v1/namespaces/test/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1026 HTTP Request: GET https://10.1.0.107:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1026 HTTP Request: GET https://10.1.0.107:16443/api/v1/namespaces/test/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:438 checking whether all units are part of the same cluster
[32mINFO    [0m httpx:_client.py:1026 HTTP Request: GET https://10.1.0.107:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1026 HTTP Request: GET https://10.1.0.107:16443/api/v1/namespaces/test/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1026 HTTP Request: GET https://10.1.0.107:16443/api/v1/namespaces/test/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1026 HTTP Request: GET https://10.1.0.107:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1026 HTTP Request: GET https://10.1.0.107:16443/api/v1/namespaces/test/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1026 HTTP Request: GET https://10.1.0.107:16443/api/v1/namespaces/test/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1026 HTTP Request: GET https://10.1.0.107:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1026 HTTP Request: GET https://10.1.0.107:16443/api/v1/namespaces/test/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1026 HTTP Request: GET https://10.1.0.107:16443/api/v1/namespaces/test/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:447 checking whether no writes to the database were missed after stopping the writes
[32mINFO    [0m httpx:_client.py:1026 HTTP Request: GET https://10.1.0.107:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1026 HTTP Request: GET https://10.1.0.107:16443/api/v1/namespaces/test/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.1.8    unsupported  02:04:35Z

App                  Version  Status  Scale  Charm                Channel  Rev  Address         Exposed  Message
postgresql-k8s       14.11    active      3  postgresql-k8s                  0  10.152.183.110  no       
postgresql-test-app           active      1  postgresql-test-app  edge     176  10.152.183.125  no       received database credentials of the first database

Unit                    Workload  Agent  Address     Ports  Message
postgresql-k8s/0        active    idle   10.1.74.83         
postgresql-k8s/1*       active    idle   10.1.74.84         Primary
postgresql-k8s/2        active    idle   10.1.74.85         
postgresql-test-app/0*  active    idle   10.1.74.78         received database credentials of the first database

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

unit-postgresql-k8s-1: 01:57:30 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: api connection broken unexpectedly
unit-postgresql-k8s-1: 01:57:36 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [94afdd] "unit-postgresql-k8s-1" cannot open api: cannot resolve "controller-service.controller-microk8s-localhost.svc.cluster.local": lookup controller-service.controller-microk8s-localhost.svc.cluster.local: i/o timeout
unit-postgresql-k8s-1: 01:57:43 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [94afdd] "unit-postgresql-k8s-1" cannot open api: cannot resolve "controller-service.controller-microk8s-localhost.svc.cluster.local": lookup controller-service.controller-microk8s-localhost.svc.cluster.local: i/o timeout
unit-postgresql-k8s-1: 01:57:50 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [94afdd] "unit-postgresql-k8s-1" cannot open api: cannot resolve "controller-service.controller-microk8s-localhost.svc.cluster.local": lookup controller-service.controller-microk8s-localhost.svc.cluster.local: i/o timeout
unit-postgresql-k8s-1: 01:57:59 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [94afdd] "unit-postgresql-k8s-1" cannot open api: cannot resolve "controller-service.controller-microk8s-localhost.svc.cluster.local": lookup controller-service.controller-microk8s-localhost.svc.cluster.local: i/o timeout

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...